version: "3"

services:

  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=tobias.hess@uni-ulm.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - traefik.http.routers.to-https.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.to-https.entrypoints=http
      - traefik.http.routers.to-https.middlewares=to-https
    ports:
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ddueruem
      POSTGRES_PASSWORD: ddueruem
      POSTGRES_DB: ddueruem
    volumes:
      - postgresdata:/var/lib/postgresql

  backend:
    build: ./backend
    volumes:
      - djangomedia:/api/media
    command: ./entrypoint.sh
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`doener.tobiasbetz.de`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    command: nginx -g 'daemon off;'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`vm-154-210.bwcloud.uni-ulm.de`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

volumes:
  postgresdata:
  djangomedia: